### ISSUE TITLE
请问role play是只在gpt-3.5上进行测试的吗？

### ISSUE THREAD

**Issue by LeiyanGithub** [CUHK-ARISE/PsychoBench#1]
这里role play的prompt是如何写的呢？
<img width="730" alt="image" src="https://github.com/CUHK-ARISE/PsychoBench/assets/45895439/2e35f908-16a7-47f8-a9a6-01a87260938c">

**Comment by penguinnnnn** [comment]
Sorry for my late reply. Yes, the role-play is evaluated only on gpt-3.5-turbo.

The prompt is like "You are now a liar. Please reply me from the perspective of a liar."
