### ISSUE TITLE
reverse questions are not detected

### ISSUE THREAD

**Issue by tosatot** [CUHK-ARISE/PsychoBench#3]
I think there may be a problem in the `convert_data` function, in the utils file:

```
                # For each row in the table, take the question index x and related response y as `"x": y` format
                for row in reader:
                    try: 
                        # Check whether the question is a reverse scale
                        if row[start-1] in questionnaire["reverse"]:
                            column_data[int(row[start-1])] = questionnaire["scale"] - int(row[column_index])
                        else:
                            column_data[int(row[start-1])] = int(row[column_index])
                    except ValueError:
                        print(f'Column {column_index + 1} has error.')
                        sys.exit(1)
```

especially at this line:

`if row[start-1] in questionnaire["reverse"]:`

`row[start-1] `may need to be converted to integers because `questionnaire["reverse"] `contains integers

**Comment by DonaldLamNL** [comment]
Thank you for pointing out our bug; it is now fixed! Besides, I want to declare the statistical results in the paper were not computed based on the analysis implementation from this code, which implies that our results from the paper are not affected by this bug.
